# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProjeto', models.CharField(max_length=50, verbose_name='Nome do Projeto')),
                ('descricaoProjeto', models.TextField(verbose_name='Descricao do Projeto')),
            ],
        ),
    ]
